config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from work_time import views
from django.contrib.auth.models import Group


admin.site.site_header = "システム管理サイト"
admin.site.index_title = "メニュー"
admin.site.unregister(Group)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", login_required(views.Index.as_view()), name="index"),
    path("", include("django.contrib.auth.urls")),
    path("sign-up/", views.SignUpView.as_view(), name="signup"),
    path("user_update/<pk>", views.UserUpdate.as_view(), name="user_update"),
    path("work_time/", views.MyWork.as_view(), name="mywork"),
    path(
        "work_time/<int:year>/<int:month>/<int:day>/",
        views.MyWork.as_view(),
        name="mywork",
    ),
    path("update/<pk>", views.Update.as_view(), name="update"),
    path("delete/<pk>", views.Delete.as_view(), name="delete"),
    path("work_index/", views.WorkIndex.as_view(), name="work_index"),
]

work_time/models.py
from django.db import models

# Create your models here.
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import AbstractUser, UserManager
from django.urls import reverse_lazy
import datetime
from django.utils import timezone


class UserManager(UserManager):
    pass


class User(AbstractUser):
    email = models.EmailField("メールアドレス", unique=False, blank=True)
    full_name = models.CharField(
        "氏名",
        blank=True,
        max_length=255,
    )

    class Meta:
        verbose_name = verbose_name_plural = _("アカウント")

    def get_absolute_url(self):
        return reverse_lazy("/")

    def __str__(self):
        return str(self.full_name)


class WorkTime(models.Model):
    """スケジュール"""

    start_time = models.TimeField("開始時間", default=datetime.time(0, 0, 0))
    end_time = models.TimeField("終了時間", default=datetime.time(0, 0, 0))
    description = models.TextField("メモ", blank=True)
    date = models.DateField("日付")
    created_at = models.DateTimeField("作成日", default=timezone.now)
    name = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="related_user",
        verbose_name="ユーザー",
    )

    class Meta:
        verbose_name = verbose_name_plural = _("勤務時間")

    def __str__(self):
        return str(self.date)

work_time/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import User, WorkTime
from django import forms
import datetime as dt


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "full_name", "password1", "password2")

    def save(self, commit=True):
        # commit=Falseだと、DBに保存されない
        user = super().save(commit=False)
        user.save()
        return user


class BS4ScheduleForm(forms.ModelForm):
    """Bootstrapに対応するためのModelForm"""

    class Meta:
        model = WorkTime
        fields = ("start_time", "end_time", "description")
        widgets = {
            "start_time": forms.TextInput(
                attrs={
                    "class": "form-control",
                }
            ),
            "end_time": forms.TextInput(
                attrs={
                    "class": "form-control",
                }
            ),
            "description": forms.Textarea(
                attrs={
                    "class": "form-control",
                }
            ),
        }

    def clean_end_time(self):
        start_time = self.cleaned_data["start_time"]
        end_time = self.cleaned_data["end_time"]
        if end_time > dt.time(hour=5):
            if end_time <= start_time:
                raise forms.ValidationError(
                    "終了時間は、開始時間よりも後にしてください"
                )
        return end_time


class SearchForm(forms.Form):
    startdate = forms.DateInput()
    enddate = forms.DateInput()

work_time/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from .forms import SignUpForm, BS4ScheduleForm
from .models import User, WorkTime
from django.urls import reverse_lazy
import datetime
from django.shortcuts import redirect
from django.views import generic
from . import mixins
from .forms import BS4ScheduleForm, SearchForm
from django.http import HttpResponse


# Create your views here.
class Index(ListView):
    # 一覧するモデルを指定 -> `object_list`で取得可能
    model = User
    template_name = "registration/index.html"


class SignUpView(CreateView):
    form_class = SignUpForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"


class UserUpdate(UpdateView):
    template_name = "registration/user_form.html"
    model = User
    fields = ["full_name", "email"]
    success_url = "/"

    def get(self, request, **kwargs):
        if User.objects.get(id=self.kwargs["pk"]) != request.user:
            return HttpResponse("不正なアクセスです。")
        return super().get(request)


class MyWork(mixins.MonthCalendarMixin, generic.CreateView):
    """月間カレンダー、週間カレンダー、スケジュール登録画面のある欲張りビュー"""

    template_name = "work_time/mywork.html"
    model = WorkTime
    date_field = "date"
    form_class = BS4ScheduleForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        month_calendar_context = self.get_month_calendar()
        context.update(month_calendar_context)
        month = self.kwargs.get("month")
        year = self.kwargs.get("year")
        day = self.kwargs.get("day")
        if year:
            context["date"] = datetime.date(
                year=int(year), month=int(month), day=int(day)
            )
        context["night_time"] = datetime.time(hour=5)
        return context

    def get(self, request, **kwargs):
        month = self.kwargs.get("month")
        year = self.kwargs.get("year")
        day = self.kwargs.get("day")
        if year:
            date = datetime.date(year=int(year), month=int(month), day=int(day))
            if WorkTime.objects.filter(date=date, name=request.user).exists():
                objects = WorkTime.objects.filter(date=date, name=request.user)
                pk = [object.id for object in objects][0]
                return redirect("/update/{}".format(pk))
        return super().get(request)

    def form_valid(self, form):
        month = self.kwargs.get("month")
        year = self.kwargs.get("year")
        day = self.kwargs.get("day")
        if month and year and day:
            date = datetime.date(year=int(year), month=int(month), day=int(day))
        else:
            date = datetime.date.today()
        mywork = form.save(commit=False)
        mywork.date = date
        mywork.name = self.request.user
        mywork.save()
        return redirect("/work_time/", year=date.year, month=date.month, day=date.day)


class Update(mixins.MonthCalendarMixin, UpdateView):
    template_name = "work_time/mywork_form.html"
    model = WorkTime
    form_class = BS4ScheduleForm
    success_url = "/work_time/"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        month_calendar_context = self.get_month_calendar()
        context.update(month_calendar_context)
        month = self.kwargs.get("month")
        year = self.kwargs.get("year")
        day = self.kwargs.get("day")
        if year:
            context["date"] = datetime.date(
                year=int(year), month=int(month), day=int(day)
            )
        context["night_time"] = datetime.time(hour=5)
        return context

    def get(self, request, **kwargs):
        if WorkTime.objects.get(id=self.kwargs["pk"]).name != request.user:
            return HttpResponse("不正なアクセスです。")
        return super().get(request)


class Delete(DeleteView):
    model = WorkTime
    # 削除したあとに移動する先（トップページ）
    success_url = "/work_time/"

    def get(self, request, **kwargs):
        if WorkTime.objects.get(id=self.kwargs["pk"]).name != request.user:
            return HttpResponse("不正なアクセスです。")
        return super().get(request)


class WorkIndex(ListView):
    # 一覧するモデルを指定 -> `object_list`で取得可能
    model = WorkTime
    template_name = "work_time/mywork_index.html"
    paginate_by = 5

    def get_queryset(self):
        query_set = WorkTime.objects.filter(name=self.request.user).order_by("-date")

        return query_set

    def post(self, request, *args, **kwargs):
        form_value = [
            self.request.POST.get("startdate", None),
            self.request.POST.get("enddate", None),
        ]
        request.session["form_value"] = form_value

        return self.get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        startdate = ""
        enddate = ""
        if "form_value" in self.request.session:
            form_value = self.request.session["form_value"]
            startdate = form_value[0]
            enddate = form_value[1]
        default_data = {
            "startdate": startdate,
            "enddate": enddate,
        }
        test_form = SearchForm(initial=default_data)  # 検索フォーム
        context["test_form"] = test_form
        context["date_range"] = ",".join([startdate, enddate])
        context["range"] = "〜".join([startdate, enddate])
        context["objects"] = WorkTime.objects.filter(name=self.request.user).order_by(
            "-date"
        )

        return context

templates/work_time/base.html
<!doctype HTML>
{% load static %}
<html lang="ja">
    <head>
        <link rel="apple-touch-icon" sizes="180x180" href="{% static 'icon_shift.png' %}"/>
        <link rel="touch-icon" sizes="192x192" href="{% static 'icon_shift.png' %}"/>
        <link rel="shortcut icon" sizes="192x192" href="{% static 'icon_shift.png' %}"/>
        <link rel="icon" sizes="192x192" href="{% static 'icon_shift.png' %}"/>
        <link rel="shortcut icon" sizes="32x32" href="{% static 'icon_shift.png' %}"/>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'mywork_index.css' %}" />
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <meta name="viewport" content="width=device-width,initial-scale=1.0,shrink-to-fit=no" />
        <title>勤務時間管理</title>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">マイページ</a>
    <button class="navbar-toggler" type="button"
      data-toggle="collapse"
      data-target="#navmenu1"
      aria-controls="navmenu1"
      aria-expanded="false"
      aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navmenu1">
       <div class="navbar-nav">
         <a class="nav-item nav-link" href="/work_time">勤務確認</a>
         <a class="nav-item nav-link" href="/work_index">勤務一覧</a>
         <form action="{% url 'logout' %}" method="post" class="nav-item nav-link">
          {% csrf_token %}
          <button class="btn btn-link p-0 text-danger"type="submit">
            ログアウト
          </button>
        </form>
    </div>
  </div>
</nav>
        <div class="container mt-3">
        {% block main %}
        <p>※コンテンツがありません。</p>
        {% endblock %}
        </div>

        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
                integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
                crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
                integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
                crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
                integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
                crossorigin="anonymous"></script>
        {% block extrajs %}{% endblock %}
    </body>
</html>

templates/work_time/index.html
{% extends "work_time/base.html" %}
{% block main %}
{% load tag_library %}
<h2>勤務一覧</h2>
<table border="1" class="table table-striped">
  <th>勤務</th>
  <th>時間</th>
{% for object in object_list|slice:":10" %}
<tr>
<td>{{ object.date|date:"Y/m/d" }}({{ object.date | date:"l"}})
{{ object.start_time }}〜{{ object.end_time }}</td>
<td>{{ object|work_time }}</td>
{% empty %}
<td>勤務がありません</td><td></td>
{% endfor %}
</tr>
</table>
{% include "work_time/pagination.html" %}
<h2>勤務合計</h2>
<table class="table text-center">
  {% if not range == '〜'　%}
  <tr class="table-info">
    <th>{{ range }}</th><th></th>
    </tr>
  {% endif %}
  <tr class="table-info">
  <th>
  <form method="POST">
    {% csrf_token %}
        <input type="date" id="startdate" name="startdate"　placeholder="年/月/日" >
        〜
        <input type="date" id="enddate" name="enddate" placeholder="年/月/日" >
        <th>
      <input type="submit" class="btn btn-info btn-lg" value="検索">
    </form>
    </th>
    </tr>
    </table>
{% if objects|date_filter:date_range%}
  <table class="table text-center">
    <tr>
      <th>合計時間</th>
      <th>深夜合計</th>
      <th>残業合計</th>
    </tr>
    <tr>
      {% for object in objects|date_filter:date_range|work_time_sum %}
      <td>{{ object }}</td>
      {% endfor %}
      </tr>
    </table>
{% else %}
<table class="table text-center">
  <tr>
    <th class="table-danger">勤務がありません。</th>
    </tr>
  </table>
{% endif %}
{% endblock %}

templates/work_time/month.html
{% load tag_library %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'month.css' %}" />
<a href="{% url 'mywork' month_previous.year month_previous.month month_previous.day %}">前月</a>
{{ month_current | date:"Y年m月" }}
<a href="{% url 'mywork' month_next.year month_next.month month_next.day %}">次月</a>

<table class="table" style="table-layout: fixed;">
    <thead>
      <tr>
          {% for w in week_names %}
                  {% if w == '土' %}
                      <td class="table-primary text-center">
                  {% elif w == '日' %}
                      <td class="table-success text-center">
                  {% else %}
                  <th class="table-info text-center">
                  {% endif %}
                   {{ w }}</th>
              {% endfor %}
      </tr>
    </thead
    <tbody>
    {% for week in month_days %}
        <tr class="text-center">
            {% for day in week %}
            {% if day|jpholiday %}
                     <td class='table-danger'>
            {% elif day.weekday == 6 %}
                     <td class='table-danger'>
            {% elif day.weekday == 5 %}
                     <td class='table-primary'>
            {% else %}
            <td>
            {% endif %}
            {% if day|day_my_shift:user %}
            <div class="maru size_normal pink1">
              <div class="letter3">
            {% else %}
            <div>
              <div>
            {% endif %}
                 <a href="{% url 'mywork' day.year day.month day.day %}">
                   {% if month_current.month != day.month %}
                   {{ day | date:"m/d" }}
                   {% else %}
                        {{ day.day }}
                   {% endif %}
                  </a>
                </div>
              </div>
                </td>
            {% endfor %}
        </tr>
    {% endfor %}
    </tbody>
</table>

templates/work_time/mywork.html
{% extends 'work_time/base.html' %}
{% block main %}
            {% include 'work_time/month.html' %}
            <hr>
          {% if date %}
            {{ date|date:"Y/m/d" }}({{ date | date:"l"}})
              <form action="" method="POST">
                {{ form.non_field_errors }}
                {% for field in form %}
                {{ field.label_tag }}
                          {{ field }}
                          {{ field.errors }}
                {% endfor %}
                {% csrf_token %}
                <button type="submit" class="btn btn-primary btn-block">送信</button>
            </form>
          {% endif %}
{% endblock %}

{% block extrajs %}
    <link rel="stylesheet" type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/timedropper/1.0/timedropper.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/timedropper/1.0/timedropper.min.js"></script>
    <script>
        $(function () {
            // timedropper
            $("#id_start_time").timeDropper({
                format: "H:mm",
                setCurrentTime: false,
            });
            $("#id_end_time").timeDropper({
                format: "H:mm",
                setCurrentTime: false,
            });
        });
    </script>
{% endblock %}

templates/work_time/mywork_form.html
{% extends 'work_time/base.html' %}
{% block main %}
            {% include 'work_time/month.html' %}
            <hr>
            {{ object.date|date:"Y/m/d" }}({{ object.date | date:"l"}})
              <form action="" method="POST">
                {{ form.non_field_errors }}
                {% for field in form %}
                {{ field.label_tag }}
                          {{ field.errors }}
                            {{ field }}
                {% endfor %}
                {% csrf_token %}
                <button type="submit" class="btn btn-primary btn-block">送信</button>
                <a class="btn  btn-danger btn-block" href="{% url 'delete' object.pk %}">削除</a>
            </form>
{% endblock %}


{% block extrajs %}
<link rel="stylesheet" type="text/css"
  href="https://cdnjs.cloudflare.com/ajax/libs/timedropper/1.0/timedropper.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/timedropper/1.0/timedropper.min.js"></script>
<script>
$(function () {
    // timedropper
    $("#id_start_time").timeDropper({
        format: "H:mm",
        setCurrentTime: false,
    });
    $("#id_end_time").timeDropper({
        format: "H:mm",
        setCurrentTime: false,
    });
});
</script>
{% endblock %}

templates/work_time/mywork_index.html
{% extends "work_time/base.html" %}
{% block main %}
{% load tag_library %}
<h2>勤務一覧</h2>
<table border="1" class="table table-striped">
  <th>勤務</th>
  <th>時間</th>
{% for object in object_list|slice:":10" %}
<tr>
<td>{{ object.date|date:"Y/m/d" }}({{ object.date | date:"l"}})
{{ object.start_time }}〜{{ object.end_time }}</td>
<td>{{ object|work_time }}</td>
{% empty %}
<td>勤務がありません</td><td></td>
{% endfor %}
</tr>
</table>
{% include "work_time/pagination.html" %}
<h2>勤務合計</h2>
<table class="table text-center">
  {% if not range == '〜'　%}
  <tr class="table-info">
    <th>{{ range }}</th><th></th>
    </tr>
  {% endif %}
  <tr class="table-info">
  <th>
  <form method="POST">
    {% csrf_token %}
        <input type="date" class="form_design" id="startdate" name="startdate"　placeholder="年/月/日" >
        〜
        <input type="date" class="form_design" id="enddate" name="enddate" placeholder="年/月/日" >
        <th>
      <input type="submit" class="btn btn-info btn-lg" value="検索">
    </form>
    </th>
    </tr>
    </table>
{% if objects|date_filter:date_range%}
  <table class="table text-center">
    <tr>
      <th>合計時間</th>
      <th>深夜合計</th>
      <th>残業合計</th>
    </tr>
    <tr>
      {% for object in objects|date_filter:date_range|work_time_sum %}
      <td>{{ object }}</td>
      {% endfor %}
      </tr>
    </table>
{% else %}
<table class="table text-center">
  <tr>
    <th class="table-danger">勤務がありません。</th>
    </tr>
  </table>
{% endif %}
{% endblock %}

templates/work_time/pagination.html
{% if is_paginated %}
<nav aria-label="Page navigation">
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
        <span class="sr-only">Previous</span>
      </a>
    </li>
    {% endif %}
    {% for num in paginator.page_range %}
    {% if page_obj.number == num %}
    <li class="page-item active">
      <span class="page-link">
        {{ num }}
        <span class="sr-only">(current)</span>
      </span>
    </li>
    {% else %}
    <li class="page-item">
      <a class="page-link" href="?page={{ num }}">{{ num }}</a>
    </li>
    {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
        <span class="sr-only">Next</span>
      </a>
    </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

templates/work_time/worktime_confirm_delete.html
{% extends "work_time/base.html" %}

{% block main %}
<h2>削除確認</h2>
<p>{{ object.title }}を本当に削除してもよろしいですか？</p>
<form method="post">
    {% csrf_token %}
    <input type="submit" value="削除" class="btn btn-danger" />
</form>
{% endblock %}